name: docker.yml
on: [push]
jobs:
  build-and-push: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up docker 
        uses: docker/setup-buildx-action@v3
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.my_secret }}
          password: ${{ secrets.my_secret1}}
      - name: build and push
        uses: docker/build-push-action@v6
        with:
         context: /Users/yusufab/Desktop/docker/redis_flask
         push: true
         tags: bootcamp98/my-name:myimage

        


      
